Web/MyPetProject.Web/Controllers/FoodsController.cs
namespace MyPetProject.Web.Controllers
{
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using MyPetProject.Data.Common.Repositories;
    using MyPetProject.Data.Models;
    using MyPetProject.Web.ViewModels.Foods;

    public class FoodsController : BaseController
    {
        private readonly IDeletableEntityRepository<FoodType> foodtypesRepository;
        private readonly IDeletableEntityRepository<Food> foodsRepository;
        private readonly IDeletableEntityRepository<Subbreed> subbreedsRepository;
        private readonly IDeletableEntityRepository<ApplicationUser> applicationsRepository;

        public FoodsController(
            IDeletableEntityRepository<FoodType> foodtypesRepository,
            IDeletableEntityRepository<Food> foodsRepository,
            IDeletableEntityRepository<Subbreed> subbreedsRepository,
            IDeletableEntityRepository<ApplicationUser> applicationsRepository)
        {
            this.foodtypesRepository = foodtypesRepository;
            this.foodsRepository = foodsRepository;
            this.subbreedsRepository = subbreedsRepository;
            this.applicationsRepository = applicationsRepository;
        }

        // GET: Foods
        public async Task<IActionResult> Index() => await this.IndexWithoutNameMethod();

        // GET: Foods/{name}
        [HttpGet("/Foods/{name}")]
        public async Task<IActionResult> Index(string name) => await this.IndexWithNameMethod(name);

        // GET: Foods/Details/{name}
        [HttpGet("/Foods/Details/{name}")]
        public async Task<IActionResult> Details(string name) => await this.DetailsMethod(name);

        // GET: Foods/Create
        [HttpGet("/Foods/Create/")]
        public IActionResult Create() => this.CreateGet();

        // POST: Foods/Create
        [HttpPost("/Foods/Create/")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FoodInputModel food)
            => await this.CreatePost(food);

        // GET: Foods/Edit/{name}
        [HttpGet("/Foods/Edit/{name}")]
        public async Task<IActionResult> Edit(string name) => await this.EditGet(name);

        // POST: Foods/Edit/{name}
        [HttpPost("/Foods/Edit/{name}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string name, FoodInputModel food)
            => await this.EditPost(name, food);

        // GET: Foods/Delete/{name}
        [HttpGet("/Foods/Delete/{name}")]
        public async Task<IActionResult> Delete(string name) => await this.DeleteGet(name);

        // POST: Foods/Delete/{name}
        [HttpPost("/Foods/Delete/{name}")]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id, string name) => await this.DeletePost(id);

        private async Task<IActionResult> IndexWithNameMethod(string name)
        {
            var result = this.foodsRepository
                            .All()
                            .Include(b => b.User)
                            .Where(x => x.FoodTypeName == name)
                            .OrderBy(x => x.Name);

            return this.View(await result.ToListAsync());
        }

        private async Task<IActionResult> DetailsMethod(string name)
        {
            if (name == null)
            {
                return this.NotFound();
            }

            var result = await this.foodsRepository
                .All()
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.Name == name);

            if (result == null)
            {
                return this.NotFound();
            }

            return this.View(result);
        }

        private IActionResult CreateGet()
        {
            if (!this.User.Claims.Any())
            {
                return this.Redirect("/ErrorPage");
            }

            this.ViewData["FoodTypeName"] = new SelectList(this.foodtypesRepository.All().OrderBy(x => x.Name), "Name", "Name");
            return this.View();
        }

        private async Task<IActionResult> CreatePost(FoodInputModel food)
        {
            if (this.ModelState.IsValid)
            {
                var result = new Food
                {
                    Name = food.Name,
                    PicUrl = food.PicUrl,
                    Description = food.Description,
                    FoodTypeName = food.FoodTypeName,
                    UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
                };
                await this.foodsRepository.AddAsync(result);
                await this.foodsRepository.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["FoodTypeName"] = new SelectList(this.foodtypesRepository.All(), "Name", "Name", food.FoodTypeName);
            return this.View(food);
        }

        private async Task<IActionResult> EditGet(string name)
        {
            if (!this.User.Claims.Any())
            {
                return this.Redirect("/ErrorPage");
            }

            if (name == null)
            {
                return this.NotFound();
            }

            var repo = await this.foodsRepository
                 .All()
                 .FirstOrDefaultAsync(x => x.Name == name);

            var result = new FoodInputModel()
            {
                Name = repo.Name,
                PicUrl = repo.PicUrl,
                Description = repo.Description,
                FoodTypeName = repo.FoodTypeName,
                UserId = repo.UserId,
            };

            if (result == null)
            {
                return this.NotFound();
            }

            if (this.User.FindFirstValue(ClaimTypes.NameIdentifier) == result.UserId || this.User.IsInRole("Administrator"))
            {
                this.ViewData["FoodTypeName"] = new SelectList(this.foodtypesRepository.All(), "Name", "Name");
                return this.View(result);
            }
            else
            {
                return this.Redirect("/ErrorPage");
            }
        }

        private async Task<IActionResult> EditPost(string name, FoodInputModel food)
        {
            if (name != food.Name)
            {
                return this.NotFound();
            }

            var oldName = this.HttpContext.Request.Path.Value.Split("/").Last();

            if (this.ModelState.IsValid)
            {
                try
                {
                    var editName = await this.foodsRepository
                        .All()
                        .FirstOrDefaultAsync(x => x.Name == oldName);

                    foreach (var currentFood in this.foodsRepository.All().Where(x => x.Name == oldName))
                    {
                        currentFood.Name = name;
                    }

                    var result = new Food
                    {
                        Name = food.Name,
                        PicUrl = food.PicUrl,
                        Description = food.Description,
                        FoodTypeName = food.FoodTypeName,
                        UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
                    };

                    this.foodsRepository.HardDelete(editName);
                    await this.foodsRepository.AddAsync(result);
                    await this.foodsRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.FoodExists(food.Name))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["FoodTypeName"] = new SelectList(this.foodtypesRepository.All(), "Name", "Name", food.FoodTypeName);
            return this.View(food);
        }

        private async Task<IActionResult> DeleteGet(string name)
        {
            if (!this.User.Claims.Any())
            {
                return this.Redirect("/ErrorPage");
            }

            if (name == null)
            {
                return this.NotFound();
            }

            var result = await this.foodsRepository
                .All()
                .Include(f => f.User)
                .FirstOrDefaultAsync(m => m.Name == name);

            if (result == null)
            {
                return this.NotFound();
            }

            if (this.User.FindFirstValue(ClaimTypes.NameIdentifier) == result.UserId || this.User.IsInRole("Administrator"))
            {
                return this.View(result);
            }
            else
            {
                return this.Redirect("/ErrorPage");
            }
        }

        private async Task<IActionResult> IndexWithoutNameMethod()
        {
            var applicationDbContext = this.foodsRepository
                            .All()
                            .Include(f => f.User);

            return this.View(await applicationDbContext.ToListAsync());
        }

        private async Task<IActionResult> DeletePost(int? id)
        {
            var result = await this.foodsRepository
                            .All()
                            .FirstOrDefaultAsync(x => x.Id == id);

            this.foodsRepository.Delete(result);
            await this.foodsRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool FoodExists(string name)
        {
            return this.foodsRepository
                .All()
                .Any(e => e.Name == name);
        }
    }
}

Web/MyPetProject.Web/Controllers/MyCollectionsController.cs
namespace MyPetProject.Web.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;
    using MyPetProject.Data.Common.Repositories;
    using MyPetProject.Data.Models;
    using MyPetProject.Web.ViewModels.MyCollection;

    public class MyCollectionsController : BaseController
    {
        private readonly IDeletableEntityRepository<Kingdom> kingdomsRepository;
        private readonly IDeletableEntityRepository<Breed> breedsRepository;
        private readonly IDeletableEntityRepository<Subbreed> subbreedsRepository;
        private readonly IDeletableEntityRepository<FoodType> foodtypesRepository;
        private readonly IDeletableEntityRepository<Food> foodsRepository;

        public MyCollectionsController(
            IDeletableEntityRepository<Kingdom> kingdomsRepository,
            IDeletableEntityRepository<Breed> breedsRepository,
            IDeletableEntityRepository<Subbreed> subbreedsRepository,
            IDeletableEntityRepository<FoodType> foodtypesRepository,
            IDeletableEntityRepository<Food> foodsRepository)
        {
            this.kingdomsRepository = kingdomsRepository;
            this.breedsRepository = breedsRepository;
            this.subbreedsRepository = subbreedsRepository;
            this.foodtypesRepository = foodtypesRepository;
            this.foodsRepository = foodsRepository;
        }

        [HttpGet("/MyKingdoms")]
        public IActionResult MyKingdoms()
        {
            MyCollectionViewModel result = this.MyKingdomsMethod();

            return this.View(result);
        }

        [HttpGet("/MyBreeds")]
        public IActionResult MyBreeds()
        {
            MyCollectionViewModel result = this.MyBreedsMethod();

            return this.View(result);
        }

        [HttpGet("/MySubbreeds")]
        public IActionResult MySubbreeds()
        {
            MyCollectionViewModel result = this.MySubbreedsMethod();

            return this.View(result);
        }

        [HttpGet("/MyFoodTypes")]
        public IActionResult MyFoodTypes()
        {
            MyCollectionViewModel result = this.MyFoodTypesMethod();

            return this.View(result);
        }

        [HttpGet("/MyFoods")]
        public IActionResult MyFoods()
        {
            MyCollectionViewModel result = this.MyFoodsMethod();

            return this.View(result);
        }

        private MyCollectionViewModel MyKingdomsMethod()
        {
            var result = new MyCollectionViewModel();

            result.Kingdoms = this.kingdomsRepository.All().Where(x => x.UserId == this.User.Claims.ToList()[0].Value);
            return result;
        }

        private MyCollectionViewModel MyBreedsMethod()
        {
            var result = new MyCollectionViewModel();

            result.Breeds = this.breedsRepository.All().Where(x => x.UserId == this.User.Claims.ToList()[0].Value);
            return result;
        }

        private MyCollectionViewModel MySubbreedsMethod()
        {
            var result = new MyCollectionViewModel();

            result.Subbreeds = this.subbreedsRepository.All().Where(x => x.UserId == this.User.Claims.ToList()[0].Value);
            return result;
        }

        private MyCollectionViewModel MyFoodTypesMethod()
        {
            var result = new MyCollectionViewModel();

            result.FoodTypes = this.foodtypesRepository.All().Where(x => x.UserId == this.User.Claims.ToList()[0].Value);
            return result;
        }

        private MyCollectionViewModel MyFoodsMethod()
        {
            var result = new MyCollectionViewModel();

            result.Foods = this.foodsRepository.All().Where(x => x.UserId == this.User.Claims.ToList()[0].Value);
            return result;
        }
    }
}

Web/MyPetProject.Web/Views/MyCollections/MyBreeds.cshtml
@using MyPetProject.Web.ViewModels.MyCollection;
@model MyCollectionViewModel;
@{
    var sectionCount = ViewContext.HttpContext.Request.Path.ToString().Split("/").Length;
    var lastSection = ViewContext.HttpContext.Request.Path.ToString().Split("/").Last();

    if (lastSection.Contains("%20"))
    {
        lastSection = lastSection.Replace("%20", " ");
    }

    ViewData["Title"] = "My Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";



    @* My Breeds *@
    @if (!Model.Breeds.Any())
    {
        <div class="text-center">
            <h1 class="display-4">My Breeds collection is empty ! :(</h1>
        </div>
        <div class="justify-content: center" style="display: flex;justify-content: center">
            @if (this.User.Claims.Any())
            {
                <p> <a asp-controller="Breeds" asp-action="Create">Create New Breed</a></p>
                <p style="margin: 0 8px;"> or </p>
            }
            <p>
                <a href="javascript:history.back()">Go Back</a>
            </p>
        </div>
    }
    else
    {
        if (sectionCount == 2)
        {
            <h1>My Breeds</h1>
        }
        if (sectionCount == 3)
        {
            <h1>@(lastSection)</h1>
        }

        @if (this.User.Claims.Any())
        {
            <p>
                <a asp-controller="Breeds" asp-action="Create">Create New Breed</a>
            </p>
        }
        <p>
            <a href="javascript:history.back()">Go Back</a>
        </p>

        <table class="table">
            <tbody>
                <div class="row mt-2 mb-4">

                    @foreach (var item in Model.Breeds)
                    {
                        <div class="card col-6 col-lg-3 text-center">
                            <a asp-controller="Subbreeds" asp-action="@item.Name">
                                <div class="card-body">
                                </div>
                                @if (!item.PicUrl.StartsWith("http"))
                                {
                                    if (!item.PicUrl.EndsWith(".jpg") && !item.PicUrl.EndsWith(".png") && !item.PicUrl.EndsWith(".jpeg"))
                                    {
                                        <img class="card-img" src="~/img/no-image.png" alt="Card image">
                                    }
                                    else
                                    {
                                        <img class="card-img" src="~/img/breeds/@item.PicUrl" alt="Card image">
                                    }
                                }
                                else
                                {
                                    <img class="card-img-top" src="@item.PicUrl" alt="Card image cap" onerror="this.onerror=null; src='https://i.imgur.com/VlZzxxX.png';">
                                }
                                <div class="card-body d-flex flex-column">
                                    <div class="mt-auto">
                                        <h5 class="card-title">@item.Name</h5>
                                        <a asp-controller="Subbreeds" asp-action="@item.Name" class="btn btn-primary">Group</a>
                                        <a asp-controller="Breeds" asp-action="Details" asp-route-id="@item.Name" class="btn btn-primary">Details</a>
                                        @{
                                            var userId = "";
                                            if (this.User.Claims.Any())
                                            {
                                                userId = this.User.Claims.ToList()[0].Value;
                                                if (item.UserId == userId)
                                                {
                                                    <a asp-controller="Breeds" asp-action="Edit" asp-route-id="@item.Name" class="btn btn-warning">Edit</a>
                                                    <a asp-controller="Breeds" asp-action="Delete" asp-route-id="@item.Name" class="btn btn-danger">Delete</a>
                                                }
                                            }
                                        }
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </tbody>
        </table>
    }
}

Web/MyPetProject.Web/Views/MyCollections/MyFoodTypes.cshtml
@using MyPetProject.Web.ViewModels.MyCollection;
@model MyCollectionViewModel;
@{
    var sectionCount = ViewContext.HttpContext.Request.Path.ToString().Split("/").Length;
    var lastSection = ViewContext.HttpContext.Request.Path.ToString().Split("/").Last();

    if (lastSection.Contains("%20"))
    {
        lastSection = lastSection.Replace("%20", " ");
    }

    ViewData["Title"] = "My Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";

    @* My FoodTypes *@
    @if (!Model.FoodTypes.Any())
    {
        <div class="text-center">
            <h1 class="display-4">My Food Types collection is empty ! :(</h1>
        </div>
        <div class="justify-content: center" style="display: flex;justify-content: center">
            @if (this.User.Claims.Any())
            {
                <p> <a asp-controller="FoodTypes" asp-action="Create">Create New Food Type</a></p>
                <p style="margin: 0 8px;"> or </p>
            }
            <p>
                <a href="javascript:history.back()">Go Back</a>
            </p>
        </div>
    }
    else
    {
        if (sectionCount == 2)
        {
            <h1>My Food Types</h1>
        }
        if (sectionCount == 3)
        {
            <h1>@(lastSection)</h1>
        }

        @if (this.User.Claims.Any())
        {
            <p>
                <a asp-controller="FoodTypes" asp-action="Create">Create New Food Type</a>
            </p>
        }
        <p>
            <a href="javascript:history.back()">Go Back</a>
        </p>

        <table class="table">
            <tbody>
                <div class="row mt-2 mb-4">

                    @foreach (var item in Model.FoodTypes)
                    {
                        <div class="card col-6 col-lg-3 text-center">
                            <a asp-controller="Foods" asp-action="@item.Name">
                                <div class="card-body">
                                </div>
                                @if (!item.PicUrl.StartsWith("http"))
                                {
                                    if (!item.PicUrl.EndsWith(".jpg") && !item.PicUrl.EndsWith(".png") && !item.PicUrl.EndsWith(".jpeg"))
                                    {
                                        <img class="card-img" src="~/img/no-image.png" alt="Card image">
                                    }
                                    else
                                    {
                                        <img class="card-img" src="~/img/foodtypes/@item.PicUrl" alt="Card image">
                                    }
                                }
                                else
                                {
                                    <img class="card-img-top" src="@item.PicUrl" alt="Card image cap" onerror="this.onerror=null; src='https://i.imgur.com/VlZzxxX.png';">
                                }
                                <div class="card-body d-flex flex-column">
                                    <div class="mt-auto">
                                        <h5 class="card-title">@item.Name</h5>
                                        <a asp-controller="Foods" asp-action="@item.Name" class="btn btn-primary">Group</a>
                                        <a asp-controller="FoodTypes" asp-action="Details" asp-route-id="@item.Name" class="btn btn-primary">Details</a>
                                        @{
                                            var userId = "";
                                            if (this.User.Claims.Any())
                                            {
                                                userId = this.User.Claims.ToList()[0].Value;
                                                if (item.UserId == userId)
                                                {
                                                    <a asp-controller="FoodTypes" asp-action="Edit" asp-route-id="@item.Name" class="btn btn-warning">Edit</a>
                                                    <a asp-controller="FoodTypes" asp-action="Delete" asp-route-id="@item.Name" class="btn btn-danger">Delete</a>
                                                }
                                            }
                                        }
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </tbody>
        </table>
    }
}

Web/MyPetProject.Web/Views/MyCollections/MyFoods.cshtml
@using MyPetProject.Web.ViewModels.MyCollection;
@model MyCollectionViewModel;
@{
    var sectionCount = ViewContext.HttpContext.Request.Path.ToString().Split("/").Length;
    var lastSection = ViewContext.HttpContext.Request.Path.ToString().Split("/").Last();

    if (lastSection.Contains("%20"))
    {
        lastSection = lastSection.Replace("%20", " ");
    }

    ViewData["Title"] = "My Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";

    @* My Foods *@
    @if (!Model.Foods.Any())
    {
        <div class="text-center">
            <h1 class="display-4">My Foods collection is empty ! :(</h1>
        </div>
        <div class="justify-content: center" style="display: flex;justify-content: center">
            @if (this.User.Claims.Any())
            {
                <p> <a asp-controller="Foods" asp-action="Create">Create New Food</a></p>
                <p style="margin: 0 8px;"> or </p>
            }
            <p>
                <a href="javascript:history.back()">Go Back</a>
            </p>
        </div>
    }
    else
    {
        if (sectionCount == 2)
        {
            <h1>My Foods</h1>
        }
        if (sectionCount == 3)
        {
            <h1>@(lastSection)</h1>
        }

        @if (this.User.Claims.Any())
        {
            <p>
                <a asp-controller="Foods" asp-action="Create">Create New Food</a>
            </p>
        }
        <p>
            <a href="javascript:history.back()">Go Back</a>
        </p>

        <table class="table">
            <tbody>
                <div class="row mt-2 mb-4">

                    @foreach (var item in Model.Foods)
                    {
                        <div class="card col-6 col-lg-3 text-center">
                            <a asp-controller="Foods" asp-action="Details" asp-route-id="@item.Name">
                                <div class="card-body">
                                </div>
                                @if (!item.PicUrl.StartsWith("http"))
                                {
                                    if (!item.PicUrl.EndsWith(".jpg") && !item.PicUrl.EndsWith(".png") && !item.PicUrl.EndsWith(".jpeg"))
                                    {
                                        <img class="card-img" src="~/img/no-image.png" alt="Card image">
                                    }
                                    else
                                    {
                                        <img class="card-img" src="~/img/foods/@item.PicUrl" alt="Card image">
                                    }
                                }
                                else
                                {
                                    <img class="card-img-top" src="@item.PicUrl" alt="Card image cap" onerror="this.onerror=null; src='https://i.imgur.com/VlZzxxX.png';">
                                }
                                <div class="card-body d-flex flex-column">
                                    <div class="mt-auto">
                                        <h5 class="card-title">@item.Name</h5>
                                        <a asp-controller="Foods" asp-action="Details" asp-route-id="@item.Name" class="btn btn-primary">Details</a>
                                        @{
                                            var userId = "";
                                            if (this.User.Claims.Any())
                                            {
                                                userId = this.User.Claims.ToList()[0].Value;
                                                if (item.UserId == userId)
                                                {
                                                    <a asp-controller="Foods" asp-action="Edit" asp-route-id="@item.Name" class="btn btn-warning">Edit</a>
                                                    <a asp-controller="Foods" asp-action="Delete" asp-route-id="@item.Name" class="btn btn-danger">Delete</a>
                                                }
                                            }
                                        }
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </tbody>
        </table>
    }
}

Web/MyPetProject.Web/Views/MyCollections/MySubbreeds.cshtml
@using MyPetProject.Web.ViewModels.MyCollection;
@model MyCollectionViewModel;
@{
    var sectionCount = ViewContext.HttpContext.Request.Path.ToString().Split("/").Length;
    var lastSection = ViewContext.HttpContext.Request.Path.ToString().Split("/").Last();

    if (lastSection.Contains("%20"))
    {
        lastSection = lastSection.Replace("%20", " ");
    }

    ViewData["Title"] = "My Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";

    @* My Subbreeds *@
    @if (!Model.Subbreeds.Any())
    {
        <div class="text-center">
            <h1 class="display-4">My Subbreeds collection is empty ! :(</h1>
        </div>
        <div class="justify-content: center" style="display: flex;justify-content: center">
            @if (this.User.Claims.Any())
            {
                <p> <a asp-controller="Subbreeds" asp-action="Create">Create New Subbreed</a></p>
                <p style="margin: 0 8px;"> or </p>
            }
            <p>
                <a href="javascript:history.back()">Go Back</a>
            </p>
        </div>
    }
    else
    {
        if (sectionCount == 2)
        {
            <h1>My Subbreeds</h1>
        }
        if (sectionCount == 3)
        {
            <h1>@(lastSection)</h1>
        }

        @if (this.User.Claims.Any())
        {
            <p>
                <a asp-controller="Subbreeds" asp-action="Create">Create New Subbreed</a>
            </p>
        }
        <p>
            <a href="javascript:history.back()">Go Back</a>
        </p>

        <table class="table">
            <tbody>
                <div class="row mt-2 mb-4">

                    @foreach (var item in Model.Subbreeds)
                    {
                        <div class="card col-6 col-lg-3 text-center">
                            <a asp-controller="Subbreeds" asp-action="Details" asp-route-id="@item.Name">
                                <div class="card-body">
                                </div>
                                @if (!item.PicUrl.StartsWith("http"))
                                {
                                    if (!item.PicUrl.EndsWith(".jpg") && !item.PicUrl.EndsWith(".png") && !item.PicUrl.EndsWith(".jpeg"))
                                    {
                                        <img class="card-img" src="~/img/no-image.png" alt="Card image">
                                    }
                                    else
                                    {
                                        <img class="card-img" src="~/img/subbreeds/@item.PicUrl" alt="Card image">
                                    }
                                }
                                else
                                {
                                    <img class="card-img-top" src="@item.PicUrl" alt="Card image cap" onerror="this.onerror=null; src='https://i.imgur.com/VlZzxxX.png';">
                                }
                                <div class="card-body d-flex flex-column">
                                    <div class="mt-auto">
                                        <h5 class="card-title">@item.Name</h5>
                                        <a asp-controller="Subbreeds" asp-action="Details" asp-route-id="@item.Name" class="btn btn-primary">Details</a>
                                        @{
                                            var userId = "";
                                            if (this.User.Claims.Any())
                                            {
                                                userId = this.User.Claims.ToList()[0].Value;
                                                if (item.UserId == userId)
                                                {
                                                    <a asp-controller="Subbreeds" asp-action="Edit" asp-route-id="@item.Name" class="btn btn-warning">Edit</a>
                                                    <a asp-controller="Subbreeds" asp-action="Delete" asp-route-id="@item.Name" class="btn btn-danger">Delete</a>
                                                }
                                            }
                                        }
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </tbody>
        </table>
    }
}