Web/MyPetProject.Web/Controllers/HabitatsController.cs
namespace MyPetProject.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using MyPetProject.Data.Common.Repositories;
    using MyPetProject.Data.Models;

    public class HabitatsController : BaseController
    {
        private readonly IDeletableEntityRepository<Kingdom> kingdomsRepository;

        public HabitatsController(
            IDeletableEntityRepository<Kingdom> kingdomsRepository)
        {
            this.kingdomsRepository = kingdomsRepository;
        }

        // GET: /HomeAnimals
        [HttpGet("/Kingdoms/HomeAnimals")]
        public async Task<IActionResult> HomeAnimals()
        {
            return await this.HomeAnimalsMethod();
        }

        // GET: /FarmAnimals
        [HttpGet("/Kingdoms/FarmAnimals")]
        public async Task<IActionResult> FarmAnimals()
        {
            return await this.FarmAnimalsMethod();
        }

        // GET: /WildAnimals
        [HttpGet("/Kingdoms/WildAnimals")]
        public async Task<IActionResult> WildAnimals()
        {
            return await this.WildAnimalMethod();
        }

        private async Task<IActionResult> HomeAnimalsMethod()
        {
            var result = this.kingdomsRepository
                            .All()
                            .Include(k => k.User)
                            .Where(a => a.IsPet == true)
                            .OrderBy(x => x.Name);

            return this.View(await result.ToListAsync());
        }

        private async Task<IActionResult> FarmAnimalsMethod()
        {
            var result = this.kingdomsRepository
                            .All()
                            .Include(k => k.User)
                            .Where(a => a.IsFarm == true)
                            .OrderBy(x => x.Name);

            return this.View(await result.ToListAsync());
        }

        private async Task<IActionResult> WildAnimalMethod()
        {
            var result = this.kingdomsRepository
                            .All()
                            .Include(k => k.User)
                            .Where(a => a.IsPet == false && a.IsFarm == false)
                            .OrderBy(x => x.Name);

            return this.View(await result.ToListAsync());
        }
    }
}

Web/MyPetProject.Web/Controllers/SubbreedsController.cs
namespace MyPetProject.Web.Controllers
{
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using MyPetProject.Data.Common.Repositories;
    using MyPetProject.Data.Models;
    using MyPetProject.Web.ViewModels.Subbreeds;

    public class SubbreedsController : BaseController
    {
        private readonly IDeletableEntityRepository<Subbreed> subbreedsRepository;
        private readonly IDeletableEntityRepository<Breed> breedsRepository;
        private readonly IDeletableEntityRepository<Kingdom> kingdomsRepository;

        public SubbreedsController(
            IDeletableEntityRepository<Subbreed> subbreedsRepository,
            IDeletableEntityRepository<Breed> breedsRepository,
            IDeletableEntityRepository<Kingdom> kingdomsRepository)
        {
            this.subbreedsRepository = subbreedsRepository;
            this.breedsRepository = breedsRepository;
            this.kingdomsRepository = kingdomsRepository;
        }

        // GET: Subbreeds
        public async Task<IActionResult> Index() => await this.IndexWithoutNameMethod();

        // GET: Subbreeds/{name}
        [HttpGet("/Subbreeds/{name}")]
        public async Task<IActionResult> Index(string name) => await this.IndexWithNameMethod(name);

        // GET: Subbreeds/Details/{name}
        [HttpGet("/Subbreeds/Details/{name}")]
        public async Task<IActionResult> Details(string name) => await this.DetailsMethod(name);

        // GET: Subbreeds/Create
        [HttpGet("/Subbreeds/Create/")]
        public IActionResult Create() => this.CreateGet();

        // POST: Subbreeds/Create
        [HttpPost("/Subbreeds/Create/")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubbreedInputModel subbreed)
            => await this.CreatePost(subbreed);

        // GET: Subbreeds/Edit/{name}
        [HttpGet("/Subbreeds/Edit/{name}")]
        public async Task<IActionResult> Edit(string name) => await this.EditGet(name);

        // POST: Breeds/Edit/{name}
        [HttpPost("/Subbreeds/Edit/{name}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string name, SubbreedInputModel subbreed)
            => await this.EditPost(name, subbreed);

        // GET: Subbreeds/Delete/{name}
        [HttpGet("/Subbreeds/Delete/{name}")]
        public async Task<IActionResult> Delete(string name) => await this.DeleteGet(name);

        // POST: Subbreeds/Delete/{name}
        [HttpPost("/Subbreeds/Delete/{name}")]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string name) => await this.DeletePost(name);

        private async Task<IActionResult> IndexWithoutNameMethod()
        {
            var result = this.subbreedsRepository
                .All()
                .Include(k => k.User)
                .OrderBy(x => x.Name);

            return this.View(await result.ToListAsync());
        }

        private async Task<IActionResult> IndexWithNameMethod(string name)
        {
            if (name.Contains(" "))
            {
                var result = this.subbreedsRepository
                    .All()
                    .Include(b => b.User)
                    .Where(x => x.BreedName.Replace("%20", " ") == name)
                    .OrderBy(x => x.Name);

                return this.View(await result.ToListAsync());
            }
            else
            {
                var result = this.subbreedsRepository
                    .All()
                    .Include(b => b.User)
                    .Where(x => x.BreedName == name);

                return this.View(await result.ToListAsync());
            }
        }

        private async Task<IActionResult> DetailsMethod(string name)
        {
            if (name == null)
            {
                return this.NotFound();
            }

            var result = await this.subbreedsRepository
                .All()
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Name == name);

            if (result == null)
            {
                return this.NotFound();
            }

            var list = this.kingdomsRepository.All().ToList();

            this.ViewData["Group"] = list.FirstOrDefault(x => x.Name == result.KingdomName).Group;
            this.ViewData["Diet"] = list.FirstOrDefault(x => x.Name == result.KingdomName).Diet;
            this.ViewData["IsPet"] = list.FirstOrDefault(x => x.Name == result.KingdomName).IsPet;
            this.ViewData["IsFarm"] = list.FirstOrDefault(x => x.Name == result.KingdomName).IsFarm;

            return this.View(result);
        }

        private IActionResult CreateGet()
        {
            if (!this.User.Claims.Any())
            {
                return this.Redirect("/ErrorPage");
            }

            this.ViewData["KingdomName"] = new SelectList(this.kingdomsRepository.All().OrderBy(x => x.Name), "Name", "Name");
            this.ViewData["BreedName"] = new SelectList(this.breedsRepository.All().OrderBy(x => x.Name), "Name", "Name");

            // this.ViewData["BreedId"] = new SelectList(this.context.Breeds, "Id", "Id");
            // this.ViewData["UserId"] = new SelectList(this.context.Users, "Id", "Id");
            return this.View();
        }

        private async Task<IActionResult> CreatePost(SubbreedInputModel subbreed)
        {
            if (this.ModelState.IsValid)
            {
                var result = new Subbreed
                {
                    Name = subbreed.Name,
                    PicUrl = subbreed.PicUrl,
                    Description = subbreed.Description,
                    UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
                    KingdomName = subbreed.KingdomName,
                    BreedName = subbreed.BreedName,
                };

                await this.subbreedsRepository.AddAsync(result);
                await this.subbreedsRepository.SaveChangesAsync();
                return this.RedirectToAction(subbreed.BreedName);
            }

            this.ViewData["KingdomName"] = new SelectList(this.kingdomsRepository.All(), "Name", "Name", subbreed.KingdomName);
            this.ViewData["BreedName"] = new SelectList(this.breedsRepository.All(), "Name", "Name", subbreed.BreedName);

            return this.View(subbreed);
        }

        private async Task<IActionResult> EditGet(string name)
        {
            if (!this.User.Claims.Any())
            {
                return this.Redirect("/ErrorPage");
            }

            if (name == null)
            {
                return this.NotFound();
            }

            var repo = await this.subbreedsRepository
                .All()
                .FirstOrDefaultAsync(x => x.Name == name);

            var result = new SubbreedInputModel()
            {
                Name = repo.Name,
                PicUrl = repo.PicUrl,
                Description = repo.Description,
                KingdomName = repo.KingdomName,
                BreedName = repo.BreedName,
                UserId = repo.UserId,
            };

            if (result == null)
            {
                return this.NotFound();
            }

            if (this.User.FindFirstValue(ClaimTypes.NameIdentifier) == result.UserId || this.User.IsInRole("Administrator"))
            {
                this.ViewData["KingdomName"] = new SelectList(this.kingdomsRepository.All().OrderBy(x => x.Name), "Name", "Name");
                this.ViewData["BreedName"] = new SelectList(this.breedsRepository.All().OrderBy(x => x.Name), "Name", "Name");
                return this.View(result);
            }
            else
            {
                return this.Redirect("/ErrorPage");
            }
        }

        private async Task<IActionResult> EditPost(string name, SubbreedInputModel subbreed)
        {
            if (name != subbreed.Name)
            {
                return this.NotFound();
            }

            var oldName = this.HttpContext.Request.Path.Value.Split("/").Last();

            if (this.ModelState.IsValid)
            {
                try
                {
                    var editName = await this.subbreedsRepository
                        .All()
                        .FirstOrDefaultAsync(x => x.Name == oldName);

                    foreach (var animal in this.subbreedsRepository.All().Where(x => x.Name == oldName))
                    {
                        animal.Name = name;
                    }

                    var result = new Subbreed
                    {
                        Name = subbreed.Name,
                        PicUrl = subbreed.PicUrl,
                        Description = subbreed.Description,
                        UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
                        KingdomName = subbreed.KingdomName,
                        BreedName = subbreed.BreedName,
                    };

                    this.subbreedsRepository.HardDelete(editName);
                    await this.subbreedsRepository.AddAsync(result);
                    await this.subbreedsRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.SubbreedExists(subbreed.Name))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(subbreed.BreedName);
            }

            this.ViewData["KingdomName"] = new SelectList(this.kingdomsRepository.All(), "Name", "Name", subbreed.KingdomName);

Web/MyPetProject.Web/Views/Habitats/FarmAnimals.cshtml
@model IEnumerable<MyPetProject.Data.Models.Kingdom>

@{
    var modelName = "Kingdom";
    var nextModelName = "Breeds";

    var sectionCount = ViewContext.HttpContext.Request.Path.ToString().Split("/").Length;
    var lastSection = ViewContext.HttpContext.Request.Path.ToString().Split("/").Last();

    if (lastSection.Contains("%20"))
    {
        lastSection = lastSection.Replace("%20", " ");
    }

    ViewData["Title"] = "Farm Animals";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb col-md-3">
            <li class="breadcrumb-item active" aria-current="page">Kingdoms</li>
            <li class="breadcrumb-item"><a asp-controller="Breeds" asp-action="Index">Breeds</a></li>
            <li class="breadcrumb-item"><a asp-controller="Subbreeds" asp-action="Index">Subbreeds</a></li>
        </ol>
    </nav>

    @if (!Model.Any())
    {
        <div class="text-center">
            <h1 class="display-4">The @(modelName + " " + lastSection) is empty ! :(</h1>
        </div>
        <div class="justify-content: center" style="display: flex;justify-content: center">
            @if (this.User.Claims.Any())
            {
                <p> <a asp-controller="@(modelName + "s")" asp-action="Create">Create New @(lastSection + " " + modelName)</a></p>
                <p style="margin: 0 8px;"> or </p>
            }
            <p><a href="javascript:history.back()">Go Back</a></p>
        </div>
    }
    else
    {
        if (sectionCount == 2)
        {
            <h1>Farm Animals</h1>
        }
        if (sectionCount == 3)
        {
            <h1>@(lastSection)</h1>
        }

        @if (this.User.Claims.Any())
        {
            <p>
                <a asp-controller="@(modelName + "s")" asp-action="Create">Create New @(modelName)</a>
            </p>
        }
        <p>
            <a href="javascript:history.back()">Go Back</a>
        </p>

        <table class="table">
            <tbody>
                <div class="row mt-2 mb-4">

                    @foreach (var item in Model)
                    {
                        <div class="card col-6 col-lg-3 text-center">
                            <a asp-controller="@(nextModelName)" asp-action="@item.Name">
                                <div class="card-body">
                                </div>
                                @if (!item.PicUrl.StartsWith("http"))
                                {
                                    if (!item.PicUrl.EndsWith(".jpg") && !item.PicUrl.EndsWith(".png") && !item.PicUrl.EndsWith(".jpeg"))
                                    {
                                        <img class="card-img" src="~/img/no-image.png" alt="Card image">
                                    }
                                    else
                                    {
                                        <img class="card-img" src="~/img/@(modelName + "s")/@item.PicUrl" alt="Card image">
                                    }
                                }
                                else
                                {
                                    <img class="card-img-top" src="@item.PicUrl" alt="Card image cap" onerror="this.onerror=null; src='https://i.imgur.com/VlZzxxX.png';">
                                }
                                <div class="card-body d-flex flex-column">
                                    <div class="mt-auto">
                                        <h5 class="card-title">@item.Name</h5>
                                        @if (nextModelName != "")
                                        {
                                            <a asp-controller="@(nextModelName)" asp-action="@item.Name" class="btn btn-primary">Group</a>
                                        }
                                        <a asp-controller="@(modelName + "s")" asp-action="Details" asp-route-id="@item.Name" class="btn btn-primary">Details</a>
                                        @{
                                            var userId = "";
                                            if (this.User.Claims.Any())
                                            {
                                                userId = this.User.Claims.ToList()[0].Value;
                                                if (item.UserId == userId || this.User.IsInRole("Administrator"))
                                                {
                                                    <a asp-controller="@(modelName + "s")" asp-action="Edit" asp-route-id="@item.Name" class="btn btn-warning">Edit</a>
                                                    <a asp-controller="@(modelName + "s")" asp-action="Delete" asp-route-id="@item.Name" class="btn btn-danger">Delete</a>
                                                }
                                            }
                                        }
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </tbody>
        </table>
    }
}

Web/MyPetProject.Web/Views/Habitats/HomeAnimals.cshtml
@model IEnumerable<MyPetProject.Data.Models.Kingdom>

@{
    var modelName = "Kingdom";
    var nextModelName = "Breeds";

    var sectionCount = ViewContext.HttpContext.Request.Path.ToString().Split("/").Length;
    var lastSection = ViewContext.HttpContext.Request.Path.ToString().Split("/").Last();

    if (lastSection.Contains("%20"))
    {
        lastSection = lastSection.Replace("%20", " ");
    }

    ViewData["Title"] = "Home Animals";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb col-md-3">
            <li class="breadcrumb-item active" aria-current="page">Kingdoms</li>
            <li class="breadcrumb-item"><a asp-controller="Breeds" asp-action="Index">Breeds</a></li>
            <li class="breadcrumb-item"><a asp-controller="Subbreeds" asp-action="Index">Subbreeds</a></li>
        </ol>
    </nav>

    @if (!Model.Any())
    {
        <div class="text-center">
            <h1 class="display-4">The @(modelName + " " + lastSection) is empty ! :(</h1>
        </div>
        <div class="justify-content: center" style="display: flex;justify-content: center">
            @if (this.User.Claims.Any())
            {
                <p> <a asp-controller="@(modelName + "s")" asp-action="Create">Create New @(lastSection + " " + modelName)</a></p>
                <p style="margin: 0 8px;"> or </p>
            }
            <p><a href="javascript:history.back()">Go Back</a></p>
        </div>
    }
    else
    {
        if (sectionCount == 2)
        {
            <h1>Home Animals</h1>
        }
        if (sectionCount == 3)
        {
            <h1>@(lastSection)</h1>
        }

        @if (this.User.Claims.Any())
        {
            <p>
                <a asp-controller="@(modelName + "s")" asp-action="Create">Create New @(modelName)</a>
            </p>
        }
        <p>
            <a href="javascript:history.back()">Go Back</a>
        </p>

        <table class="table">
            <tbody>
                <div class="row mt-2 mb-4">

                    @foreach (var item in Model)
                    {
                        <div class="card col-6 col-lg-3 text-center">
                            <a asp-controller="@(nextModelName)" asp-action="@item.Name">
                                <div class="card-body">
                                </div>
                                @if (!item.PicUrl.StartsWith("http"))
                                {
                                    if (!item.PicUrl.EndsWith(".jpg") && !item.PicUrl.EndsWith(".png") && !item.PicUrl.EndsWith(".jpeg"))
                                    {
                                        <img class="card-img" src="~/img/no-image.png" alt="Card image">
                                    }
                                    else
                                    {
                                        <img class="card-img" src="~/img/@(modelName + "s")/@item.PicUrl" alt="Card image">
                                    }
                                }
                                else
                                {
                                    <img class="card-img-top" src="@item.PicUrl" alt="Card image cap" onerror="this.onerror=null; src='https://i.imgur.com/VlZzxxX.png';">
                                }
                                <div class="card-body d-flex flex-column">
                                    <div class="mt-auto">
                                        <h5 class="card-title">@item.Name</h5>
                                        @if (nextModelName != "")
                                        {
                                            <a asp-controller="@(nextModelName)" asp-action="@item.Name" class="btn btn-primary">Group</a>
                                        }
                                        <a asp-controller="@(modelName + "s")" asp-action="Details" asp-route-id="@item.Name" class="btn btn-primary">Details</a>
                                        @{
                                            var userId = "";
                                            if (this.User.Claims.Any())
                                            {
                                                userId = this.User.Claims.ToList()[0].Value;
                                                if (item.UserId == userId || this.User.IsInRole("Administrator"))
                                                {
                                                    <a asp-controller="@(modelName + "s")" asp-action="Edit" asp-route-id="@item.Name" class="btn btn-warning">Edit</a>
                                                    <a asp-controller="@(modelName + "s")" asp-action="Delete" asp-route-id="@item.Name" class="btn btn-danger">Delete</a>
                                                }
                                            }
                                        }
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </tbody>
        </table>
    }
}

Web/MyPetProject.Web/Views/Habitats/WildAnimals.cshtml
@model IEnumerable<MyPetProject.Data.Models.Kingdom>

@{
    var modelName = "Kingdom";
    var nextModelName = "Breeds";

    var sectionCount = ViewContext.HttpContext.Request.Path.ToString().Split("/").Length;
    var lastSection = ViewContext.HttpContext.Request.Path.ToString().Split("/").Last();

    if (lastSection.Contains("%20"))
    {
        lastSection = lastSection.Replace("%20", " ");
    }

    ViewData["Title"] = "Wild Animals";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb col-md-3">
            <li class="breadcrumb-item active" aria-current="page">Kingdoms</li>
            <li class="breadcrumb-item"><a asp-controller="Breeds" asp-action="Index">Breeds</a></li>
            <li class="breadcrumb-item"><a asp-controller="Subbreeds" asp-action="Index">Subbreeds</a></li>
        </ol>
    </nav>

    @if (!Model.Any())
    {
        <div class="text-center">
            <h1 class="display-4">The @(modelName + " " + lastSection) is empty ! :(</h1>
        </div>
        <div class="justify-content: center" style="display: flex;justify-content: center">
            @if (this.User.Claims.Any())
            {
                <p> <a asp-controller="@(modelName + "s")" asp-action="Create">Create New @(lastSection + " " + modelName)</a></p>
                <p style="margin: 0 8px;"> or </p>
            }
            <p><a href="javascript:history.back()">Go Back</a></p>
        </div>
    }
    else
    {
        if (sectionCount == 2)
        {
            <h1>Wild Animals</h1>
        }
        if (sectionCount == 3)
        {
            <h1>@(lastSection)</h1>
        }

        @if (this.User.Claims.Any())
        {
            <p>
                <a asp-controller="@(modelName + "s")" asp-action="Create">Create New @(modelName)</a>
            </p>
        }
        <p>
            <a href="javascript:history.back()">Go Back</a>
        </p>

        <table class="table">
            <tbody>
                <div class="row mt-2 mb-4">

                    @foreach (var item in Model)
                    {
                        <div class="card col-6 col-lg-3 text-center">
                            <a asp-controller="@(nextModelName)" asp-action="@item.Name">
                                <div class="card-body">
                                </div>
                                @if (!item.PicUrl.StartsWith("http"))
                                {
                                    if (!item.PicUrl.EndsWith(".jpg") && !item.PicUrl.EndsWith(".png") && !item.PicUrl.EndsWith(".jpeg"))
                                    {
                                        <img class="card-img" src="~/img/no-image.png" alt="Card image">
                                    }
                                    else
                                    {
                                        <img class="card-img" src="~/img/@(modelName + "s")/@item.PicUrl" alt="Card image">
                                    }
                                }
                                else
                                {
                                    <img class="card-img-top" src="@item.PicUrl" alt="Card image cap" onerror="this.onerror=null; src='https://i.imgur.com/VlZzxxX.png';">
                                }
                                <div class="card-body d-flex flex-column">
                                    <div class="mt-auto">
                                        <h5 class="card-title">@item.Name</h5>
                                        @if (nextModelName != "")
                                        {
                                            <a asp-controller="@(nextModelName)" asp-action="@item.Name" class="btn btn-primary">Group</a>
                                        }
                                        <a asp-controller="@(modelName + "s")" asp-action="Details" asp-route-id="@item.Name" class="btn btn-primary">Details</a>
                                        @{
                                            var userId = "";
                                            if (this.User.Claims.Any())
                                            {
                                                userId = this.User.Claims.ToList()[0].Value;
                                                if (item.UserId == userId || this.User.IsInRole("Administrator"))
                                                {
                                                    <a asp-controller="@(modelName + "s")" asp-action="Edit" asp-route-id="@item.Name" class="btn btn-warning">Edit</a>
                                                    <a asp-controller="@(modelName + "s")" asp-action="Delete" asp-route-id="@item.Name" class="btn btn-danger">Delete</a>
                                                }
                                            }
                                        }
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </tbody>
        </table>
    }
}