Web/MyPetProject.Web/Controllers/BreedsController.cs
namespace MyPetProject.Web.Controllers
{
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using MyPetProject.Data.Common.Repositories;
    using MyPetProject.Data.Models;
    using MyPetProject.Web.ViewModels.Breeds;

    public class BreedsController : BaseController
    {
        private readonly IDeletableEntityRepository<Subbreed> subbreedsRepository;
        private readonly IDeletableEntityRepository<Breed> breedsRepository;
        private readonly IDeletableEntityRepository<Kingdom> kingdomsRepository;
        private readonly IDeletableEntityRepository<ApplicationUser> applicationsRepository;

        public BreedsController(
            IDeletableEntityRepository<Subbreed> subbreedsRepository,
            IDeletableEntityRepository<Breed> breedsRepository,
            IDeletableEntityRepository<Kingdom> kingdomsRepository,
            IDeletableEntityRepository<ApplicationUser> applicationsRepository)
        {
            this.subbreedsRepository = subbreedsRepository;
            this.breedsRepository = breedsRepository;
            this.kingdomsRepository = kingdomsRepository;
            this.applicationsRepository = applicationsRepository;
        }

        // GET: Breeds
        public async Task<IActionResult> Index() => await this.IndexWithoutNameMethod();

        // GET: Breeds/{name}
        [HttpGet("/Breeds/{name}")]
        public async Task<IActionResult> Index(string name) => await this.IndexWithNameMethod(name);

        // GET: Breeds/Details/{name}
        [HttpGet("/Breeds/Details/{name}")]
        public async Task<IActionResult> Details(string name) => await this.DetailsMethod(name);

        // GET: Breeds/Create
        [HttpGet("/Breeds/Create/")]
        public IActionResult Create() => this.CreateGet();

        // POST: Breeds/Create
        [HttpPost("/Breeds/Create/")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BreedInputModel breed) => await this.CreatePost(breed);

        // GET: Breeds/Edit/{name}
        [HttpGet("/Breeds/Edit/{name}")]
        public async Task<IActionResult> Edit(string name) => await this.EditGet(name);

        // POST: Breeds/Edit/{name}
        [HttpPost("/Breeds/Edit/{name}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string name, BreedInputModel breed)
            => await this.EditPost(name, breed);

        // GET: Breeds/Delete/{name}
        [HttpGet("/Breeds/Delete/{name}")]
        public async Task<IActionResult> Delete(string name) => await this.DeleteGet(name);

        // POST: Breeds/Delete/{name}
        [HttpPost("/Breeds/Delete/{name}")]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string name) => await this.DeletePost(name);

        private async Task<IActionResult> IndexWithoutNameMethod()
        {
            var result = this.breedsRepository
                            .All()
                            .Include(b => b.User)
                            .OrderBy(x => x.Name);

            return this.View(await result.ToListAsync());
        }

        private async Task<IActionResult> IndexWithNameMethod(string name)
        {
            var result = this.breedsRepository
                            .All()
                            .Include(b => b.User)
                            .Where(x => x.KingdomName == name)
                            .OrderBy(x => x.Name);

            return this.View(await result.ToListAsync());
        }

        private async Task<IActionResult> DetailsMethod(string name)
        {
            if (name == null)
            {
                return this.NotFound();
            }

            var result = await this.breedsRepository
                .All()
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Name == name);

            if (result == null)
            {
                return this.NotFound();
            }

            var list = this.kingdomsRepository.All().ToList();

            this.ViewData["Group"] = list.FirstOrDefault(x => x.Name == result.KingdomName).Group;
            this.ViewData["Diet"] = list.FirstOrDefault(x => x.Name == result.KingdomName).Diet;
            this.ViewData["IsPet"] = list.FirstOrDefault(x => x.Name == result.KingdomName).IsPet;
            this.ViewData["IsFarm"] = list.FirstOrDefault(x => x.Name == result.KingdomName).IsFarm;

            return this.View(result);
        }

        private IActionResult CreateGet()
        {
            if (!this.User.Claims.Any())
            {
                return this.Redirect("/ErrorPage");
            }

            this.ViewData["UserId"] = new SelectList(this.applicationsRepository.All(), "Id", "Id");
            this.ViewData["KingdomName"] = new SelectList(this.kingdomsRepository.All().OrderBy(x => x.Name), "Name", "Name");
            return this.View();
        }

        private async Task<IActionResult> CreatePost(BreedInputModel breed)
        {
            if (this.ModelState.IsValid)
            {
                var result = new Breed
                {
                    Name = breed.Name,
                    PicUrl = breed.PicUrl,
                    Description = breed.Description,
                    UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
                    KingdomName = breed.KingdomName,
                };
                await this.breedsRepository.AddAsync(result);
                await this.breedsRepository.SaveChangesAsync();
                return this.RedirectToAction(breed.KingdomName);
            }

            this.ViewData["UserId"] = new SelectList(this.applicationsRepository.All(), "Id", "Id", breed.UserId);
            this.ViewData["KingdomName"] = new SelectList(this.kingdomsRepository.All(), "Name", "Name", breed.KingdomName);

            return this.View(breed);
        }

        private async Task<IActionResult> EditGet(string name)
        {
            if (!this.User.Claims.Any())
            {
                return this.Redirect("/ErrorPage");
            }

            if (name == null)
            {
                return this.NotFound();
            }

            var repo = await this.breedsRepository
                .All()
                .FirstOrDefaultAsync(x => x.Name == name);

            var result = new BreedInputModel()
            {
                Name = repo.Name,
                PicUrl = repo.PicUrl,
                Description = repo.Description,
                KingdomName = repo.KingdomName,
                UserId = repo.UserId,
            };

            if (result == null)
            {
                return this.NotFound();
            }

            if (this.User.FindFirstValue(ClaimTypes.NameIdentifier) == result.UserId || this.User.IsInRole("Administrator"))
            {
                this.ViewData["UserId"] = new SelectList(this.applicationsRepository.All(), "Id", "Id", this.breedsRepository.All().Include(x => x.UserId));
                this.ViewData["KingdomName"] = new SelectList(this.kingdomsRepository.All(), "Name", "Name");

                return this.View(result);
            }
            else
            {
                return this.Redirect("/ErrorPage");
            }
        }

        private async Task<IActionResult> EditPost(string name, BreedInputModel breed)
        {
            if (name != breed.Name)
            {
                return this.NotFound();
            }

            var oldName = this.HttpContext.Request.Path.Value.Split("/").Last();

            if (this.ModelState.IsValid)
            {
                try
                {
                    var editName = await this.breedsRepository
                        .All()
                        .FirstOrDefaultAsync(x => x.Name == oldName);

                    foreach (var animals in this.subbreedsRepository.All().Where(x => x.BreedName == oldName))
                    {
                        animals.BreedName = name;
                    }

                    var result = new Breed
                    {
                        Id = breed.Id,
                        Name = breed.Name,
                        PicUrl = breed.PicUrl,
                        Description = breed.Description,
                        UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
                        KingdomName = breed.KingdomName,
                    };

                    this.breedsRepository.HardDelete(editName);
                    await this.breedsRepository.AddAsync(result);
                    await this.breedsRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.BreedExists(breed.Name))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(breed.KingdomName);
            }

            this.ViewData["UserId"] = new SelectList(this.applicationsRepository.All(), "Id", "Id", breed.UserId);
            this.ViewData["KingdomName"] = new SelectList(this.kingdomsRepository.All(), "Name", "Name", breed.KingdomName);

            return this.View(breed);
        }

        private async Task<IActionResult> DeleteGet(string name)
        {
            if (!this.User.Claims.Any())
            {
                return this.Redirect("/ErrorPage");
            }

            if (name == null)
            {
                return this.NotFound();
            }

            var result = await this.breedsRepository
                .All()
                .Include(b => b.User)

Web/MyPetProject.Web/Controllers/HomeController.cs
namespace MyPetProject.Web.Controllers
{
    using System;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using MyPetProject.Data.Common.Repositories;
    using MyPetProject.Data.Models;
    using MyPetProject.Web.ViewModels;

    public class HomeController : BaseController
    {
        private readonly IDeletableEntityRepository<Kingdom> kingdomsRepository;
        private readonly IDeletableEntityRepository<Breed> breedsRepository;
        private readonly IDeletableEntityRepository<Subbreed> subbreedsRepository;
        private readonly IDeletableEntityRepository<FoodType> foodtypesRepository;
        private readonly IDeletableEntityRepository<Food> foodsRepository;

        public HomeController(
            IDeletableEntityRepository<Kingdom> kingdomsRepository,
            IDeletableEntityRepository<Breed> breedsRepository,
            IDeletableEntityRepository<Subbreed> subbreedsRepository,
            IDeletableEntityRepository<FoodType> foodtypesRepository,
            IDeletableEntityRepository<Food> foodsRepository)
        {
            this.kingdomsRepository = kingdomsRepository;
            this.breedsRepository = breedsRepository;
            this.subbreedsRepository = subbreedsRepository;
            this.foodtypesRepository = foodtypesRepository;
            this.foodsRepository = foodsRepository;
        }

        public IActionResult Index()
        {
            this.TodayRandomEntityMethod();

            return this.View();
        }

        [HttpGet("/Groups")]
        public IActionResult Groups()
        {
            return this.View();
        }

        [HttpGet("/About")]
        public IActionResult About()
        {
            return this.View();
        }

        [HttpGet("/ErrorPage")]
        public IActionResult ErrorPage()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }

        private void TodayRandomEntityMethod()
        {
            Random r = new Random(DateTime.Now.Day);

            int totalKingdoms = this.kingdomsRepository.All().Count();
            int totalBreeds = this.breedsRepository.All().Count();
            int totalSubreeds = this.subbreedsRepository.All().Count();
            int totalFoodTypes = this.foodtypesRepository.All().Count();
            int totalFoods = this.foodsRepository.All().Count();

            int offsetKingdoms = r.Next(1, totalKingdoms);
            int offsetBreeds = r.Next(1, totalBreeds);
            int offsetSubreeds = r.Next(1, totalSubreeds);
            int offsetFoodTypes = r.Next(1, totalFoodTypes);
            int offsetFoods = r.Next(1, totalFoods);

            var randomKingdom = this.kingdomsRepository.All().Skip(offsetKingdoms - 1).FirstOrDefault();
            var randomBreed = this.breedsRepository.All().Skip(offsetBreeds - 1).FirstOrDefault();
            var randomSubbreed = this.subbreedsRepository.All().Skip(offsetSubreeds - 1).FirstOrDefault();
            var randomFoodType = this.foodtypesRepository.All().Skip(offsetFoodTypes - 1).FirstOrDefault();
            var randomFood = this.foodsRepository.All().Skip(offsetFoods - 1).FirstOrDefault();

            this.ViewData["RandomKingdom"] = randomKingdom;
            this.ViewData["RandomBreed"] = randomBreed;
            this.ViewData["RandomSubbreed"] = randomSubbreed;
            this.ViewData["RandomFoodType"] = randomFoodType;
            this.ViewData["RandomFood"] = randomFood;

            this.ViewData["bGroup"] = this.kingdomsRepository.All().FirstOrDefault(x => x.Name == randomBreed.KingdomName).Group;
            this.ViewData["bDiet"] = this.kingdomsRepository.All().FirstOrDefault(x => x.Name == randomBreed.KingdomName).Diet;
            this.ViewData["bIsPet"] = this.kingdomsRepository.All().FirstOrDefault(x => x.Name == randomBreed.KingdomName).IsPet;
            this.ViewData["bIsFarm"] = this.kingdomsRepository.All().FirstOrDefault(x => x.Name == randomBreed.KingdomName).IsFarm;

            this.ViewData["sGroup"] = this.kingdomsRepository.All().FirstOrDefault(x => x.Name == randomSubbreed.KingdomName).Group;
            this.ViewData["sDiet"] = this.kingdomsRepository.All().FirstOrDefault(x => x.Name == randomSubbreed.KingdomName).Diet;
            this.ViewData["sIsPet"] = this.kingdomsRepository.All().FirstOrDefault(x => x.Name == randomSubbreed.KingdomName).IsPet;
            this.ViewData["sIsFarm"] = this.kingdomsRepository.All().FirstOrDefault(x => x.Name == randomSubbreed.KingdomName).IsFarm;
        }
    }
}

Web/MyPetProject.Web/Controllers/SearchController.cs
namespace MyPetProject.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using MyPetProject.Data.Common.Repositories;
    using MyPetProject.Data.Models;
    using MyPetProject.Web.ViewModels.Search;

    public class SearchController : BaseController
    {
        private readonly IDeletableEntityRepository<Kingdom> kingdomsRepository;
        private readonly IDeletableEntityRepository<Breed> breedsRepository;
        private readonly IDeletableEntityRepository<Subbreed> subbreedsRepository;
        private readonly IDeletableEntityRepository<FoodType> foodtypesRepository;
        private readonly IDeletableEntityRepository<Food> foodsRepository;

        public SearchController(
            IDeletableEntityRepository<Kingdom> kingdomsRepository,
            IDeletableEntityRepository<Breed> breedsRepository,
            IDeletableEntityRepository<Subbreed> subbreedsRepository,
            IDeletableEntityRepository<FoodType> foodtypesRepository,
            IDeletableEntityRepository<Food> foodsRepository)
        {
            this.kingdomsRepository = kingdomsRepository;
            this.breedsRepository = breedsRepository;
            this.subbreedsRepository = subbreedsRepository;
            this.foodtypesRepository = foodtypesRepository;
            this.foodsRepository = foodsRepository;
        }

        [HttpGet("/SearchKingdoms")]
        public IActionResult SearchKingdoms()
        {
            var result = this.SearchMethod();

            return this.View(result);
        }

        [HttpGet("/SearchBreeds")]
        public IActionResult SearchBreeds()
        {
            var result = this.SearchMethod();

            return this.View(result);
        }

        [HttpGet("/SearchSubbreeds")]
        public IActionResult SearchSubbreeds()
        {
            var result = this.SearchMethod();

            return this.View(result);
        }

        [HttpGet("/SearchFoodTypes")]
        public IActionResult SearchFoodTypes()
        {
            var result = this.SearchMethod();

            return this.View(result);
        }

        [HttpGet("/SearchFoods")]
        public IActionResult SearchFoods()
        {
            var result = this.SearchMethod();

            return this.View(result);
        }

        private SearchViewModel SearchMethod()
        {
            var result = new SearchViewModel();

            result.Kingdoms = this.kingdomsRepository.All();
            result.Breeds = this.breedsRepository.All();
            result.Subbreeds = this.subbreedsRepository.All();
            result.FoodTypes = this.foodtypesRepository.All();
            result.Foods = this.foodsRepository.All();
            return result;
        }
    }
}

Web/MyPetProject.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <main class="text-center">
        <div>
            <h1>About</h1>
            <p>
                The site is made with <span style="color:darkred">❤️</span> for the animals.
                <br>At first it was suppose to be only about pet animals, but I think all animals should get the same love.
                <br>I tried to create section trying to distinguish each one of them as close as possible.
                <br><a href="~/Identity/Account/Register">Register</a> or <a href="~/Identity/Account/Login">Login</a> to use the privilege of creating and managing your animals and foods.
                <br>
                <br><span style="color:red;">Important ! :</span> To get <span style="color:red;">Administrator</span> role you need to navigate yourself to upper-right corner where your <span style="color:red;">Account name</span> is.
                <br>By writing the correct <span style="color:red;">"Admin Password"</span> and clicking on <span style="color:red;">"Become Admin"</span>, you need to <span style="color:red;">Logout</span> and <span style="color:red;">Login</span> again so your new role can be applied.
            </p>
        </div>

        <div>
            <h2>Guide to the site</h2>
            <p>
                There is the <a asp-controller="Home" asp-action="Index">Home</a> page, where you can check all the animals of the day.
                <br><br>There is the <a asp-controller="Home" asp-action="Groups">Groups</a> page, where you can choose an animal according to its group. They are divided into animal group type and its diet. Here they are...
            </p>
        </div>
        <div class="row" style="justify-content: center;">
            <div class="col-lg-3">
                <ul style="list-style-type:none;">
                    <li>There are five types of animal groups.</li>
                    <li><h3>Groups</h3></li>
                    <li><a asp-controller="Kingdoms" asp-action="Mammals">Mammals</a></li>
                    <li><a asp-controller="Kingdoms" asp-action="Birds">Birds</a></li>
                    <li><a asp-controller="Kingdoms" asp-action="Fish">Fish</a></li>
                    <li><a asp-controller="Kingdoms" asp-action="Reptiles">Reptiles & Amphibians</a></li>
                    <li><a asp-controller="Kingdoms" asp-action="Insects">Insects & Arachnids</a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <ul style="list-style-type:none;">
                    <li>There are three types of animal diet.</li>
                    <li><h3>Diet</h3></li>
                    <li><a asp-controller="Kingdoms" asp-action="Herbivores">Herbivores</a></li>
                    <li><a asp-controller="Kingdoms" asp-action="Carnivores">Carnivores</a></li>
                    <li><a asp-controller="Kingdoms" asp-action="Omnivores">Omnivores</a></li>
                </ul>
            </div>
        </div>
        <div>
            <p>
                There are three dropdown menus called "Categories", "Habitat" and "Foods"...
            </p>
        </div>
        <div class="row" style="justify-content: center;">
            <div class="col-lg-3">
                <ul style="list-style-type:none; ">
                    <li>Animals are separated in three categories.</li>
                    <li><h3>Categories</h3></li>
                    <li><a asp-controller="Kingdoms" asp-action="Index">Kingdoms</a></li>
                    <li><a asp-controller="Breeds" asp-action="Index">Breeds</a></li>
                    <li><a asp-controller="Subbreeds" asp-action="Index">Subbreeds</a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <ul style="list-style-type:none;">
                    <li>Three types of habitats separating the animals.</li>
                    <li><h3>Habitat</h3></li>
                    <li><a asp-controller="Kingdoms" asp-action="HomeAnimals">Home Animals</a></li>
                    <li><a asp-controller="Kingdoms" asp-action="FarmAnimals">Farm Animals</a></li>
                    <li><a asp-controller="Kingdoms" asp-action="WildAnimals">Wild Animals</a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <ul style="list-style-type:none;">
                    <li>Animals need to eat too, here's a catalogue where foods can be added.</li>
                    <li><h3>Foods</h3></li>
                    <li><a asp-controller="FoodType" asp-action="HomeAnimals">Food Types</a></li>
                    <li><a asp-controller="Food" asp-action="HomeAnimals">Foods</a></li>
                </ul>
            </div>
        </div>
        <div>
            <p>
                The <a asp-controller="Search" asp-action="SearchKingdoms">Search</a> page is as advanced as I could have made it.
                <br> - It has search field where you can search by everything except the Description column.
                <br> - A dynamic menu on the left where people can mark/unmark what they are looking for.
                <br> - It has all the Categories and Foods dropdown menus.
                <br> - You can also click each entity to navigate to its collection or description if there is no collection attached to it.
                <br> - Pagination is implemented.
            </p>
        </div>
    </main>
</div>

Web/MyPetProject.Web/Views/Home/Groups.cshtml
@{
    ViewData["Title"] = "Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts
{
    <link href="~/css/groups.css" rel="stylesheet" />
}

<table style="border-collapse: collapse;">
    <tbody class="row-cols-sm-2" style="">
        <tr class="central_text text-center">
            @{
                for (int i = 1; i <= 8; i++)
                {
                    var item = "";
                    if (i == 1) { item = "Insects"; }
                    if (i == 2) { item = "Carnivores"; }
                    if (i == 3) { item = "Omnivores"; }
                    if (i == 4) { item = "Herbivores"; }
                    if (i == 5) { item = "Reptiles"; }
                    if (i == 6) { item = "Birds"; }
                    if (i == 7) { item = "Mammals"; }
                    if (i == 8) { item = "Fish"; }

                    <td class="moon_container moon@(i)">
                        <a href="~/Kingdoms/@(item)">
                            <img class="moon moon@(i)" src="~/img/groups/@(item.ToLower()).jpg">
                        </a>
                    </td>
                    <td class=" moon_container moon@(i)">
                        <a href="~/Kingdoms/@(item)">
                            @if (i == 1) { item = "Insects & Arachnids"; }
                            @if (i == 5) { item = "Reptiles & Amphibians"; }
                            <h5 class="moon moon@(i)" style="text-align:center">@(item)</h5>
                        </a>
                    </td>
                }
                <td>
                    <span><h1 id="group">Groups</h1></span>
                </td>
            }
        </tr>
    </tbody>
</table>

Web/MyPetProject.Web/Views/Home/MyBreeds.cshtml
@using MyPetProject.Web.ViewModels.MyCollection;
@model MyCollectionViewModel;
@{
    var sectionCount = ViewContext.HttpContext.Request.Path.ToString().Split("/").Length;
    var lastSection = ViewContext.HttpContext.Request.Path.ToString().Split("/").Last();

    if (lastSection.Contains("%20"))
    {
        lastSection = lastSection.Replace("%20", " ");
    }

    ViewData["Title"] = "My Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";



    @* My Breeds*@
    @if (!Model.Breeds.Any())
    {
        <div class="text-center">
            <h1 class="display-4">My Breeds collection is empty ! :(</h1>
        </div>
        <div class="justify-content: center" style="display: flex;justify-content: center">
            @if (this.User.Claims.Any())
            {
                <p> <a asp-controller="Breeds" asp-action="Create">Create New Breed</a></p>
                <p style="margin: 0 8px;"> or </p>
            }
            <p>
                <a href="javascript:history.back()">Go Back</a>
            </p>
        </div>
    }
    else
    {
        if (sectionCount == 2)
        {
            <h1>My Breeds</h1>
        }
        if (sectionCount == 3)
        {
            <h1>@(lastSection)</h1>
        }

        @if (this.User.Claims.Any())
        {
            <p>
                <a asp-controller="Breeds" asp-action="Create">Create New Breed</a>
            </p>
        }
        <p>
            <a href="javascript:history.back()">Go Back</a>
        </p>

        <table class="table">
            <tbody>
                <div class="row mt-2 mb-4">

                    @foreach (var item in Model.Breeds)
                    {
                        <div class="card col-6 col-lg-3 text-center">
                            <a asp-controller="Subbreeds" asp-action="@item.Name">
                                <div class="card-body">
                                </div>
                                @if (!item.PicUrl.StartsWith("http"))
                                {
                                    if (!item.PicUrl.EndsWith(".jpg") && !item.PicUrl.EndsWith(".png") && !item.PicUrl.EndsWith(".jpeg"))
                                    {
                                        <img class="card-img" src="~/img/no-image.png" alt="Card image">
                                    }
                                    else
                                    {
                                        <img class="card-img" src="~/img/breeds/@item.PicUrl" alt="Card image">
                                    }
                                }
                                else
                                {
                                    <img class="card-img" src="@item.PicUrl" alt="Card image">
                                }
                                <div class="card-body d-flex flex-column">
                                    <div class="mt-auto">
                                        <h5 class="card-title">@item.Name</h5>
                                        <a asp-controller="Subbreeds" asp-action="@item.Name" class="btn btn-primary">Group</a>
                                        <a asp-controller="Breeds" asp-action="Details" asp-route-id="@item.Name" class="btn btn-primary">Details</a>
                                        @{
                                            var userId = "";
                                            if (this.User.Claims.Any())
                                            {
                                                userId = this.User.Claims.ToList()[0].Value;
                                                if (item.UserId == userId)
                                                {
                                                    <a asp-controller="Breeds" asp-action="Edit" asp-route-id="@item.Name" class="btn btn-warning">Edit</a>
                                                    <a asp-controller="Breeds" asp-action="Delete" asp-route-id="@item.Name" class="btn btn-danger">Delete</a>
                                                }
                                            }
                                        }
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </tbody>
        </table>
    }
}